spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: newpassword123

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: COSF

  mail:
    host: smtp.gmail.com
    port: 587
    username: m.abdoulaye.gueye@gmail.com
    password: hwfnljuwqlkuqpxt # pas ton vrai mot de passe Gmail !
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

